apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:aZHTuVeIYuUvKJnJWkqVfyKf7/e897Pd5HRYS97li3NlOwWCXedf8qpVRCx3kbL4btUp1lwpCITuQTgeva6IjGFPxIon4wSapgg=,iv:taGIzFIxh/Lsr4xStzr7HrhSFaTCef7wnxpM7es/XPw=,tag:WYdArcf1S+ryuP6nkdlA/w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16mx5tq55gfgkckfhvrz5uptdmjcjttj7dmal065n7qjkkg9c3q2szwhudu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcUsvelVIc0VLbDIxUTRo
        azY0UG4zZXM0NERsRW1QYTJyeENCcmh6Nm13CnMzL0U0blo0YlFWdHhBdUJzZE9y
        bFlqNEJyNlU5aVZwRzhZTVJmMWxhUTAKLS0tIElGZWZMbVNGS1JobXQ5OC9nZUJE
        Vm44a0FtZjYxVzZLaWRjc2RVU2wwN1EK+jeVtx6L/zoL9ZD/DJkrbg/D7aOPd/Kr
        C1CcGRqGKVRHfKx4u23TWcb7PkKwD6Xx47epR/Yh4hZKBuNARHehIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T19:21:12Z"
  mac: ENC[AES256_GCM,data:w3jcggq+yKQ2Py58JNpddY3ByGpVJ/V1WLbLxZa6Wvu8GU234RKGSNZ0qL+pXWN1irYi4Dc0mSqtQTB6LcbX7UmWFKt7Vnfi3bWGq6sdmrb3BrOUsOelUcnP4a+7tgS7XuhBlXdant5A9ARJ08+r+FpOTm0MKpmU57nStStGJJ4=,iv:2oxEgNdEBnbRZFTAd40BihnbvkU4weM3IFcncvEmV1g=,tag:T7nTBlvXa9W62Xy7ksqfgg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
